In [1]:
from adodbapi import ProgrammingError
from webcolors import names

a = 15
b = 4

print(a)
print(b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a//b)

15
4
19
11
60
3.75
3
50625
3

In [7]:
a = 13
b = 33

print(a>b)
print(a>=b)
print(a<b)
print(a<=b)
print(a==b)
print(a!=b)

False
False
True
True
False
True

In [5]:
a = True
b = False

print(a and b)
print(b or a)
print(not a)
print(not b)

False
True
False
True

In [6]:
a = 10
b = a

print(a)
print(b)

b += a
print(b)

b -= a
print(b)

b *= a
print(b)

10
10
20
10
100

In [9]:
from math import pi

r = int(input("Enter radius: "))

area = pi * r * r
print(area)

12.566370614359172

In [8]:
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print(f"Sum:{num1+num2}")

Sum:3

In [12]:
num1 = 10
num2 = 5
if num1 > num2:
    print(f"The number {num1} > {num2}")

The number 10 > 5

In [13]:
for i in range(1,21):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

In [14]:
for i in range(0,11,2):
    print(i)

0
2
4
6
8
10

In [17]:
a = 10
b = 20
c = a

print(a is not b)
print(a is b)
print(a is c)
print(c is a)

True
False
True
True

In [18]:
x = int(input("Enter x: "))
list = [1,2,3,4,5,6]

if x not in list:
    print("X is not in list")
else:
    print("X is in list")

X is in list

In [1]:
a = 10
b = 20
a,b = b,a
print(a,b)

20 10

In [2]:
a = 10
b = 20

a = a+b
b = a-b
a = a+b
print(a,b)

40 10

In [4]:
a = 10
b = 20

if a>b:
    print("Largest:a")
else:
    print("Largest:b")

Largest:b

In [6]:
str1 = "Hello World"
rev = ""

for char in str1:
    rev = char + rev

print(rev)

dlroW olleH

In [10]:
c = 'i'

if c  in 'aeiou':
    print("Vowel")
else:
    print("Not a Vowel")

Vowel

In [12]:
fact = 1
n = 5

for i in range(1,n+1):
    fact = fact * i
print(fact)

120

In [14]:
num = 7
is_prime = True

if(num < 2):
    is_prime = False
else:
    for i in range(2,num):
        if(num%i == 0):
            is_prime = False
            break
if(is_prime):
    print("prime")
else:
    print("not prime")

prime

In [19]:
for i in range(1,7):
    for j in range(i):
        print("*",end="")
    print()
print()

*
**
***
****
*****
******

In [16]:
for i in range(1,7):
    print(i * "*",end="")
    print()

*
**
***
****
*****
******

In [2]:
num = 123
sum = 0
while(num >= 10):
    temp = num
    while(num > 0):
        rem = num % 10
        num = num // 10
        sum  = sum * 10 + rem
print(sum)

321

In [42]:
text = "Python Programming"
# Slicing [start:end:step]
print(text[0:6])    # Python
print(text[7:])     # Programming
print(text[:6])     # Python
print(text[::2])    # Pto rgamn (every 2nd character)
print(text[::-1])   # Reverse string: "gnimmargorP nohtyP"
print(text.split(',', 3))
text.replace(" "," ")

Python
Programming
Python
Pto rgamn
gnimmargorP nohtyP
['Python Programming']

'Python Programming'

In [36]:
text = "A man a plan a canal Panama"
cleaned = text.replace(" ", "").lower()
print(cleaned)

amanaplanacanalpanama

In [2]:
team = ['Virat','Santhosh','Rohit','Bumrah']
team1 = ['Kusal Mendis','Dhoni','Raina','Jadeja']
team.remove('Santhosh')
team.append('Sachin')
team.pop()
team.extend(team1)
print(team)

['Virat', 'Rohit', 'Bumrah', 'Kusal Mendis', 'Dhoni', 'Raina', 'Jadeja']

In [6]:
matrix = [
    [1,0,0],
    [0,1,0],
    [0,0,1]
]
matrix[0][0]

1

In [14]:
li = [1,4,3]
li.sort()
print(li)

[1, 3, 4]

In [12]:
student = {
    "name": "Emma",
    "age": 16,
    "Grade": "10th",
    "Subjects":["Math","science","English"]
}

print(student["age"])
print(student["Subjects"][1])
print(student["Subjects"])

16
science
['Math', 'science', 'English']

In [18]:
John = {
    "Phone":"555-1234",
    "City":"New York",
    "Has Whatsapp":True,
}

John["email"] = "john@email.com"
John.update({"City": "Boston"})
del John["Has Whatsapp"]
print(John)

{'Phone': '555-1234', 'City': 'Boston', 'email': 'john@email.com'}

In [23]:
def dict(words):
    animal={}
    for word in words:
        animal[word]=len(word)
    print(animal)

dict(words = ["cat","dog","elephant"])

{'cat': 3, 'dog': 3, 'elephant': 8}

In [26]:
def count_characters(text):
    dic = {}
    for char in text:
        if char == " ":
            continue
        else:
            if char in dic:
                dic[char] +=1
            else:
                dic[char] = 1
    print(dic)

count_characters("hello")

{'h': 1, 'e': 1, 'l': 2, 'o': 1}

In [9]:
l1 = [3,2,1,12,4,3,5,1]

l2 = []
for num in l1:
   if num not in l2:
       l2.append(num)
print(l2)

[3, 2, 1, 12, 4, 5]

In [10]:
a = [1, 3, 2, 3, 4, 3, 2, 1, 3]

print(max(set(a), key=a.count))

3

In [11]:
list1 = [1,2,3,4,5]
list2 = [1,7,8,9]

found = False

for i in list1:
    for j in list2:
        if i == j:
            found = True
            break
    if found:
        break

if found:
    print("Common element exists")
else:
    print("No common elements")

Common element exists

In [15]:
b = [1, [2, 3], [4, [5, 6]], 7]
result = []

def flat(lst):
    for item in lst:
        if type(item) == list:
            flat(item)
        else:
            result.append(item)
flat(b)
result

[1, 2, 3, 4, 5, 6, 7]

In [23]:
def group_anagrams(words):
    anagram_dict = {}

    for word in words:
        key = ''.join(sorted(word))   # sort letters

        if key in anagram_dict:
            anagram_dict[key].append(word)
        else:
            anagram_dict[key] = [word]

    return list(anagram_dict.values())


words = ["eat", "tea", "tan", "ate", "nat", "bat"]
print(group_anagrams(words))

TypeError: 'str' object is not callable

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr.ndim

1

In [6]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [12]:
arr = np.ones([5,2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
arr = np.full(5,2)
arr

array([2, 2, 2, 2, 2])

In [16]:
arr = np.empty([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr = np.random.randn(5)
arr
print(type(arr))

<class 'numpy.ndarray'>

In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr.shape
arr.size
re = arr.reshape(2,3)
re
ravel = re.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [14]:
arr
arr1 = np.array([7,8,9,10,11,12])
print(arr + arr1)
print(arr - arr1)
print(arr * arr1)
print(arr // arr1)
srt = np.sqrt(arr1)
srt

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
[0 0 0 0 0 0]

array([2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162])

In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[0:3]
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(matrix[0:2,:])
for ind, x in np.ndenumerate(matrix):
    print(ind, x)

[[1 2 3]
 [4 5 6]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9

In [25]:
arr = np.array([1,2,3,4,5])
view  = arr[1:3]
view

array([2, 3])

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.split(arr,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [6]:
print(np.sum(arr))
print(np.max(arr))
np.min(arr)

45
9

np.int64(1)

In [8]:
arr = np.array([1,2,3,4,5,6])
result = np.where(arr>3,"low","high")
result

array(['high', 'high', 'high', 'low', 'low', 'low'], dtype='<U4')

In [10]:
arr[(arr>3)]

array([4, 5, 6])

In [20]:
arr[0:3]

array([1, 2, 3])

In [3]:
import pandas as pd

s = pd.Series([10,20,30,40,50,'abcd'])
s

0      10
1      20
2      30
3      40
4      50
5    abcd
dtype: object

In [4]:
s.values

array([10, 20, 30, 40, 50, 'abcd'], dtype=object)

In [6]:
s.name = 'Numbers'
s

0      10
1      20
2      30
3      40
4      50
5    abcd
Name: Numbers, dtype: object

In [8]:
s[0]
s[0:2]

0    10
1    20
Name: Numbers, dtype: object

In [11]:
fruit_protein = {
    "Avacado": 2.0,
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 0.1,
    "Mango": 0.8,
    "Cherries": 1.0
}
s2 = pd.Series(fruit_protein,name = "Protein")
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     0.1
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [16]:
s2>1
s2[s2>1]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Name: Protein, dtype: float64

In [17]:
s2["Apple"] = 2.9

In [18]:
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     0.1
Mango           0.8
Cherries        1.0
Apple           2.9
Name: Protein, dtype: float64

In [21]:
import numpy as np
data = {
    "Name": ["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age": [25,30,35,np.nan,29,25],
    "Department": ["HR","IT","Finance","IT","HR","HR"],
    "Salary": [50000,60000,70000,62000,np.nan,50000]
}

data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [22]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [24]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [25]:
df.tail(2)

    Name   Age Department   Salary
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [26]:
df.loc[1:3, ["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [27]:
df.shape

(6, 4)

In [28]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [30]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [32]:
df["Salary"] = df["Salary"] + 5000
df["Salary"]

0    60000.0
1    70000.0
2    80000.0
3    72000.0
4        NaN
5    60000.0
Name: Salary, dtype: float64

In [33]:
df.rename(columns = {"Department": "Dept"}, inplace = True)

In [34]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  60000.0
1      Bob  30.0       IT  70000.0
2  Charlie  35.0  Finance  80000.0
3    David   NaN       IT  72000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  60000.0

In [36]:
df["Salary"].unique()

array([60000., 70000., 80000., 72000.,    nan])

In [37]:
df["Promoted Salary"] = df["Salary"] * 10

In [38]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  60000.0         600000.0
1      Bob  30.0       IT  70000.0         700000.0
2  Charlie  35.0  Finance  80000.0         800000.0
3    David   NaN       IT  72000.0         720000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  60000.0         600000.0

In [39]:
df.dropna()

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  60000.0         600000.0
1      Bob  30.0       IT  70000.0         700000.0
2  Charlie  35.0  Finance  80000.0         800000.0
5    Alice  25.0       HR  60000.0         600000.0

In [40]:
df.dropna(how = "any")

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  60000.0         600000.0
1      Bob  30.0       IT  70000.0         700000.0
2  Charlie  35.0  Finance  80000.0         800000.0
5    Alice  25.0       HR  60000.0         600000.0

In [42]:
df["Salary"].fillna(df["Salary"].mean())

0    60000.0
1    70000.0
2    80000.0
3    72000.0
4    68400.0
5    60000.0
Name: Salary, dtype: float64

In [1]:
squared = lambda x : x*x
print(squared(5))

25

In [2]:
add = lambda x, y: x + y
print(add(1,2))

3